FROM php:8.4-fpm-alpine

RUN apt update && apt install -y \
    libc6 libpq-dev libicu-dev libfreetype6-dev libjpeg62-turbo-dev libpng-dev libzip-dev unzip zip vim cron supervisor npm \
    && pecl install redis \
    && pecl install raphf && docker-php-ext-enable raphf \
    && pecl install pecl_http && docker-php-ext-enable http

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

## Enable php extensions
RUN docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-configure pgsql -with-pgsql=/usr/local/pgsql \
    && docker-php-ext-configure pcntl --enable-pcntl \
    && docker-php-ext-install -j$(nproc) gd pdo pdo_mysql pdo_pgsql pgsql zip mysqli gettext pcntl bcmath \
    && docker-php-ext-enable redis mysqli

RUN echo "alias ll='ls -alhF --color'" >> ~/.bashrc

WORKDIR /var/www/html/
