FROM php:7.2-apache

ENV APACHE_DOCUMENT_ROOT=/var/www/html/public

RUN apt update && apt install -y \
    libc6 libpq-dev libicu-dev libfreetype6-dev libjpeg62-turbo-dev libpng-dev libzip-dev unzip zip vim cron supervisor npm \
    && pecl install redis

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

## Enable php extensions
RUN docker-php-ext-configure gd \
    && docker-php-ext-configure pgsql -with-pgsql=/usr/local/pgsql \
    && docker-php-ext-configure pcntl --enable-pcntl \
    && docker-php-ext-install -j$(nproc) gd pdo pdo_mysql pdo_pgsql pgsql zip mysqli gettext pcntl bcmath \
    && docker-php-ext-enable redis mysqli

RUN sed -ri -e 's!/var/www/html!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/sites-available/*.conf \
	&& sed -ri -e 's!/var/www/html!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/apache2.conf /etc/apache2/conf-available/*.conf

RUN a2enmod rewrite

RUN echo "alias ll='ls -alhF --color'" >> ~/.bashrc

WORKDIR /var/www/html/

EXPOSE 80
CMD ["apache2-foreground"]