FROM php:8.4-fpm-alpine AS build

RUN apk add --no-cache \
    bash wget libstdc++ msmtp perl procps shadow vim supervisor ${PHPIZE_DEPS} \
    libzip-dev libpq-dev libpng-dev libjpeg-turbo-dev libwebp-dev freetype-dev \
    icu-dev libxml2-dev zlib-dev pcre-dev && \
 	pecl install redis && \
 	docker-php-ext-configure gd --with-freetype --with-jpeg --with-webp && \
 	docker-php-ext-configure pcntl --enable-pcntl && \
 	docker-php-ext-install gd pdo_pgsql intl exif zip xml bcmath gettext pcntl && \
 	docker-php-ext-enable redis

FROM php:8.4-fpm-alpine

RUN apk add --no-cache \
    bash wget libstdc++ msmtp perl procps shadow vim supervisor \
    libzip libpq libpng libjpeg-turbo libwebp freetype \
    icu-libs zlib

RUN rm -rf /usr/local/lib/php/extensions/* && \
    rm -rf /usr/local/etc/php/conf.d/*

COPY --from=build /usr/local/lib/php/extensions/ /usr/local/lib/php/extensions/
COPY --from=build /usr/local/etc/php/conf.d/*.ini /usr/local/etc/php/conf.d/

RUN echo 'memory_limit = 2048M' > /usr/local/etc/php/conf.d/app.ini && \
	echo 'post_max_size = 128M' >> /usr/local/etc/php/conf.d/app.ini && \
	echo 'upload_max_filesize = 128M' >> /usr/local/etc/php/conf.d/app.ini && \
	echo 'max_execution_time = 60' >> /usr/local/etc/php/conf.d/app.ini

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

WORKDIR /var/www/html
