FROM php:8.4-fpm-alpine

RUN apk add --no-cache --virtual build-essentials bash wget libstdc++ msmtp perl procps shadow \
    libzip libpq-dev libpng libjpeg-turbo libwebp freetype icu libxml2-dev \
    git vim supervisor postgresql-client icu-dev icu-libs zlib-dev g++ make automake autoconf libzip-dev \
    libpng-dev libwebp-dev libjpeg-turbo-dev freetype-dev pcre-dev ${PHPIZE_DEPS} && \
    pecl install redis && \
    docker-php-ext-configure gd --enable-gd --with-freetype --with-jpeg --with-webp && \
    docker-php-ext-configure pcntl --enable-pcntl && \
    docker-php-ext-install gd && \
    docker-php-ext-install pdo && \
    docker-php-ext-install pdo_pgsql && \
    docker-php-ext-install intl && \
    docker-php-ext-install opcache && \
    docker-php-ext-install exif && \
    docker-php-ext-install zip && \
    docker-php-ext-install pcntl && \
    docker-php-ext-install xml && \
    docker-php-ext-install soap && docker-php-ext-enable soap && \
    docker-php-ext-enable redis && \
    echo 'memory_limit = 2048M' >> /usr/local/etc/php/conf.d/docker-php-memlimit.ini && \
    echo 'post_max_size = 128M' >> /usr/local/etc/php/conf.d/docker-php-memlimit.ini && \
    echo 'upload_max_filesize = 128M' >> /usr/local/etc/php/conf.d/docker-php-memlimit.ini && \
    echo 'max_execution_time = 60' >> /usr/local/etc/php/conf.d/docker-php-memlimit.ini

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

RUN echo "alias ll='ls -alhF --color'" >> ~/.bashrc

WORKDIR /var/www/html/
